import { FormaPagamento, IEntity } from '../types';
import { IsAutoGeneratedID, Column, IsUnique, ValidateParcelas } from '../decorators/entity.decorators';
import { IsEmail, IsNotEmpty, IsString, Length, Validate, isNotEmpty } from 'class-validator';
import { ItemCompra } from './itemCompra.entity';

export class Compra implements IEntity {
  constructor() {
    this.ItemCompra = [];
  }

  @Column()
  id: string;

  @Column()
  idUsuario: string;

  @Column(ItemCompra)
  ItemCompra: ItemCompra[];

  @IsNotEmpty()
  @Column()
  formaPagamento: FormaPagamento;

  @IsNotEmpty()
  @Validate(ValidateParcelas)
  @Column()
  parcelas: number;

  @Column()
  valorPparcelas: number;

  @Column(Date)
  dataCompra: Date;

  @Column()
  total: number;
}