import { FormaPagamento, IEntity, Entity } from '../types';
import { IsAutoGeneratedID, Column, IsUnique, ValidateParcelas } from '../decorators/entity.decorators';
import { IsEmail, IsNotEmpty, IsString, Length, Validate, isNotEmpty } from 'class-validator';
import { ItemCompra } from './itemCompra.entity';

export class Compra extends Entity {
  constructor() {
    super();
    this.ItemCompra = [];
  }

  @Column()
  id: string;

  @Column()
  idUsuario: string;

  @Column(ItemCompra)
  ItemCompra: ItemCompra[];

  @IsNotEmpty()
  @Column()
  formaPagamento: FormaPagamento = FormaPagamento.DEBITO;

  @IsNotEmpty()
  @Validate(ValidateParcelas)
  @Column()
  parcelas: number = 1;

  @Column()
  valorPparcelas: number;

  @Column(Date)
  dataCompra: Date;

  @Column()
  total: number;
}