import { FormaPagamento, IEntity, Entity } from '../types';
import { IsAutoGeneratedID, Column } from '../decorators/entity.decorators';
import { IsNotEmpty, Validate } from 'class-validator';
import { ItemCompra } from './itemCompra.entity';
import { ValidateParcelas } from './compra.decorators';

export class Compra extends Entity {
  constructor() {
    super();
    this.ItemCompra = [];
  }

  @IsAutoGeneratedID()
  @Column()
  id: string;

  @Column()
  idUsuario: string;

  @Column(ItemCompra)
  ItemCompra: ItemCompra[];

  @IsNotEmpty()
  @Column()
  formaPagamento: FormaPagamento = FormaPagamento.DEBITO;

  @IsNotEmpty()
  @Validate(ValidateParcelas)
  @Column()
  parcelas: number = 1;

  @Column()
  valorPparcelas: number;

  @Column(Date)
  dataCompra: Date;

  @Column()
  total: number;
}