import { IEntity } from '../types';
import { IsAutoGeneratedID, Column, IsUnique } from '../decorators/entity.decorators';
import { IsEmail, IsNotEmpty, IsString, Length } from 'class-validator';

export class ItemCompra implements IEntity {
    @Column()
    idLivro: string;

    @Column()
    quantidade: number;

    @Column()
    preco: number;
}