import { Entity } from '../types';
import { IsNotEmpty, IsString, Length, MinDate, isNotEmpty } from 'class-validator';
import { IsUnique, IsAutoGeneratedID, CheckFK, Column } from '../decorators/entity.decorators'

export class Endereco extends Entity {
    @IsNotEmpty()
    @Column()
    pais: string;

    @Column()
    estado: string;

    @IsNotEmpty()
    @Column()
    cidade: string;

    @Column()
    bairro: string;

    @Column()
    rua: string;

    @Column()
    numero: string;

    @Column()
    complemento: string;

    @Column()
    cep: string;
}