import { IEntity } from '../types';
import * as EntityDecorators from '../decorators/entity.decorators';
import { IsEmail, IsNotEmpty, IsString, Length } from 'class-validator';

export class Autor implements IEntity {
  @IsString()
  @IsNotEmpty({ message: 'O ID autor não deve ser vazio' })
  @EntityDecorators.IsAutoGeneratedID()
  @EntityDecorators.Column()
  id: string;

  @IsString()
  @IsNotEmpty()
  @EntityDecorators.Column()
  nome: string;

  @IsEmail()
  @IsNotEmpty()
  @EntityDecorators.IsUnique()
  @EntityDecorators.Column()
  email: string;

  @IsString()
  @IsNotEmpty()
  @Length(20, 50)
  @EntityDecorators.Column()
  biografia: string;

  @EntityDecorators.Column()
  dataCadastro: Date;
}
