import { IsNotEmpty, IsString, Length } from 'class-validator';
import { Column, IsAutoGeneratedID, IsUnique } from '../decorators/entity.decorators';

export class Categoria {
    @IsUnique()
    @IsString()
    @IsNotEmpty({message: 'O ID da categoria não deve ser vazio'})
    @IsAutoGeneratedID()
    @Column()
    id: string;

    @IsString()
    @IsNotEmpty({message: 'O campo descrição não deve ser vazio'})
    @IsUnique()
    @Column()
    descricao: string;
}
