import { Entity } from '../types';
import { IsNotEmpty, IsString, Length, MinDate } from 'class-validator';
import { IsUnique, IsAutoGeneratedID, CheckFK, Column } from '../decorators/entity.decorators'

export class Livro extends Entity {
    @IsUnique()
    @IsString()
    @IsNotEmpty({message: 'O ID do livro não deve ser vazio'})
    @IsAutoGeneratedID()
    @Column()
    id: string;

    @IsString()
    @IsNotEmpty()
    @Column()
    nome: string;

    @IsString()
    @IsNotEmpty()
    @Length(500)
    @Column()
    resumo: string;

    @IsNotEmpty()
    @Length(100)
    @Column()
    sumario: string;

    @Column()
    preco: number;

    @Column()
    paginas: number;
    
    @IsUnique()
    @Column()
    ISBN: string;

    @MinDate(new Date(), {message: 'Data de publicação inválida'})
    @Column(Date)
    dataPublicacao: Date;

    @IsString()
    @IsNotEmpty()
    @CheckFK('Categoria', 'id')
    @Column()
    categoria: string;

    @CheckFK('Autor', 'id')
    @Column()
    autor: string;
}
